In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [9]:
arr = np.array(my_list)

In [10]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.random.rand(5)

array([0.4555649 , 0.70058846, 0.08922634, 0.98831203, 0.19819801])

In [39]:
np.random.rand(5,5)

array([[0.78037354, 0.31590963, 0.4529701 , 0.5232664 , 0.60403496],
       [0.33442227, 0.468301  , 0.56647118, 0.88792058, 0.27257804],
       [0.13369556, 0.03896078, 0.71959304, 0.69358186, 0.8748424 ],
       [0.03674404, 0.93802047, 0.92311386, 0.54206893, 0.1051902 ],
       [0.02120305, 0.09558441, 0.76976606, 0.55436433, 0.24449913]])

In [44]:
np.random.randn(4,4)

array([[ 0.66423337,  0.82837607,  0.70497813,  0.48333452],
       [ 0.19766304,  0.25508789,  0.74393808, -0.56646197],
       [-0.32307657,  0.7492069 ,  0.88542376,  0.04209349],
       [ 1.72310009, -0.18361079, -0.28371963,  1.08232147]])

In [51]:
np.random.randint(1,100,10)

array([14, 93, 30, 65, 70, 71, 28, 44, 59, 24])

In [52]:
arr = np.arange(25)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr = np.random.randint(0,50,10)

In [55]:
ranarr

array([ 5, 37, 35, 43, 30,  2, 36,  7, 48,  4])

In [58]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
ranarr

array([ 5, 37, 35, 43, 30,  2, 36,  7, 48,  4])

In [60]:
ranarr.max()

48

In [61]:
ranarr.min()

2

In [62]:
ranarr.argmax()

8

In [63]:
ranarr

array([ 5, 37, 35, 43, 30,  2, 36,  7, 48,  4])

In [64]:
ranarr.argmin()

5

In [65]:
arr.shape

(25,)

In [66]:
arr = arr.reshape(5,5)

In [67]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr.dtype

dtype('int32')

In [71]:
from numpy.random import randint

In [72]:
randint(2,10)

9